# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
    vmImage: 'ubuntu-latest'
    
variables:
  buildConfiguration: 'Release'
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: true
    projects: 'src/SimplCommerce.WebHost/SimplCommerce.WebHost.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'



